/**
 * GenerationTheater — staged progress card shown while a storyboard is being
 * turned into a video. Used in two places:
 *   - the review view, while "Generate Code" runs (phase="code")
 *   - the processing view, while scenes render / assemble (phase="render" | "assemble")
 * so the user sees the same stage strip, per-scene tiles and tips throughout.
 */

import { Clock, Info } from 'lucide-react';

const STAGES = [
    { id: 'draft', label: 'Storyboard drafted', icon: '📋' },
    { id: 'code', label: 'Writing animation code', icon: '⌨️' },
    { id: 'render', label: 'Rendering frames', icon: '🎬' },
    { id: 'voice', label: 'Generating narration', icon: '🎙️' },
    { id: 'assemble', label: 'Stitching final video', icon: '🪡' },
];

const TIPS = [
    'Manim is the open-source engine 3Blue1Brown uses for math animations.',
    'Each scene renders independently — a failure only retries that one scene.',
    'Narration runs locally via Piper TTS, so generation never blocks on a vendor API.',
    'If a scene fails, its Manim code is still saved — you can inspect what the LLM tried.',
    'Scenes render two at a time, matched to the renderer\u2019s CPU count.',
    'Manim code is generated by Gemini, with an automatic repair pass if a scene fails to compile.',
];

export type GenerationPhase = 'code' | 'render' | 'assemble';

/**
 * Rough wall-clock estimate, in minutes, for the work still ahead.
 *
 * Was a fixed "3-6 minutes", which stopped being true once storyboards could
 * run to 12 scenes: a user watching a 12-scene render against a 6-minute
 * promise concludes the job has hung. Derived from the two real costs — a
 * sequential Gemini call per scene during code-gen, and a Manim render per
 * scene two at a time — rather than a constant.
 */
function estimateMinutes(phase: GenerationPhase, total: number): string {
    if (total <= 0) return '1–2 minutes';
    // ~8s per sequential code-gen call; ~35s per render at 2 in parallel.
    const seconds = phase === 'code' ? total * 8 + 20 : (total / 2) * 35 + 25;
    const lo = Math.max(1, Math.round(seconds / 60));
    return `${lo}–${lo + Math.max(1, Math.round(lo * 0.6))} minutes`;
}

interface GenerationTheaterProps {
    phase: GenerationPhase;
    /** Scenes finished for the current phase. */
    done: number;
    total: number;
    /**
     * Per-scene status from the API, used to colour the tiles during render.
     * Omitted during code-gen, where `done` is the only signal we have.
     */
    sceneStatuses?: Array<string | undefined>;
}

export function GenerationTheater({ phase, done, total, sceneStatuses }: GenerationTheaterProps) {
    const activeStageIdx = phase === 'code' ? 1 : phase === 'render' ? 2 : 4;
    const isAssembling = phase === 'assemble';

    const headline = isAssembling
        ? 'Assembling final video'
        : total > 0
            ? `Scene ${Math.min(done + 1, total)} of ${total}`
            : 'Getting started';

    const footnote = isAssembling
        ? 'Final stitch — about 10 seconds'
        : phase === 'code'
            ? done === 0
                ? 'Asking the model for the first scene’s animation code…'
                : `${done} scene${done === 1 ? '' : 's'} coded — keep going`
            : done === 0
                ? 'Warming up the renderer…'
                : `${done} scene${done === 1 ? '' : 's'} done — keep going`;

    const tip = TIPS[(done + (isAssembling ? 1 : 0)) % TIPS.length];

    return (
        <div className="glass-card rounded-2xl p-5 space-y-5">
            {/* Estimate banner */}
            <div className="flex flex-col sm:flex-row items-start sm:items-center gap-3 rounded-xl border border-white/10 bg-white/3 px-4 py-3">
                <div className="flex items-center gap-2 shrink-0">
                    <Clock className="w-4 h-4 text-slate-300" />
                    <span className="text-sm font-medium text-slate-100">
                        Estimated time: {estimateMinutes(phase, total)}
                    </span>
                </div>
                <span className="text-xs text-slate-500 sm:border-l sm:border-white/10 sm:pl-3">
                    You can leave this tab open — generation continues even if you switch away.
                </span>
            </div>

            {/* Stage strip */}
            <div className="flex items-center justify-between gap-2">
                {STAGES.map((stage, idx) => {
                    const stageDone = idx < activeStageIdx;
                    const active = idx === activeStageIdx;
                    return (
                        <div
                            key={stage.id}
                            className="flex-1 flex flex-col items-center gap-1.5 min-w-0"
                        >
                            <div
                                className={`w-9 h-9 rounded-full flex items-center justify-center text-base transition-all ${stageDone
                                    ? 'bg-white/10 border border-white/30 text-white/90'
                                    : active
                                        ? 'bg-white/15 border border-white/50 text-white shadow-lg shadow-white/10 animate-pulse'
                                        : 'bg-white/2 border border-white/10 text-white/30'
                                    }`}
                            >
                                {stageDone ? '✓' : stage.icon}
                            </div>
                            <span
                                className={`text-[10px] uppercase tracking-wider truncate max-w-full ${active ? 'text-white' : stageDone ? 'text-white/50' : 'text-white/30'
                                    }`}
                            >
                                {stage.label}
                            </span>
                        </div>
                    );
                })}
            </div>

            <div className="h-px bg-white/5" />

            {/* Per-scene live status grid — each tile pulses while its scene is
                the in-flight one and fills in as scenes complete. */}
            <div>
                <div className="flex items-center justify-between mb-2.5">
                    <p className="text-xs text-white/60 font-medium">{headline}</p>
                    <p className="text-[11px] text-white/40 font-mono">
                        {done} / {total}
                    </p>
                </div>
                <div className="grid grid-cols-12 gap-1">
                    {Array.from({ length: total }).map((_, i) => {
                        const sceneStatus = sceneStatuses?.[i];
                        const isComplete = sceneStatuses ? sceneStatus === 'completed' : i < done;
                        const isProcessing =
                            !isComplete && !isAssembling && (sceneStatus === 'processing' || i === done);
                        const isFailed = sceneStatus === 'failed';
                        return (
                            <div
                                key={i}
                                className={`h-1.5 rounded-full transition-all ${isFailed
                                    ? 'bg-danger/70'
                                    : isComplete
                                        ? 'bg-white/85'
                                        : isProcessing
                                            ? 'bg-white/40 animate-pulse'
                                            : 'bg-white/8'
                                    }`}
                                title={`Scene ${i + 1}: ${sceneStatus || (i < done ? 'completed' : 'pending')}`}
                            />
                        );
                    })}
                </div>
            </div>

            {/* Footer microcopy — rotates based on stage */}
            <p className="text-[11px] text-white/40 italic text-center">{footnote}</p>

            {/* "Did you know?" tip — rotates as scenes complete so the user sees
                a fresh fact every minute or so. Deterministic index, no timer. */}
            <div className="flex items-start gap-2 rounded-lg border border-white/8 bg-white/2 px-3 py-2.5">
                <Info className="w-3.5 h-3.5 text-slate-400 shrink-0 mt-0.5" />
                <p className="text-[11px] text-slate-400 leading-relaxed">
                    <span className="text-slate-300 font-medium">Did you know?</span> {tip}
                </p>
            </div>
        </div>
    );
}
